---
title: "R Notebook"
output: html_notebook
---
```{r}
library(readxl) 
library(gsubfn) 
library(stats) 
library(BSDA)
library(ggplot2)
library(cowplot)
```

```{r}
#Base de datos
DB <-read.csv("/Users/rudiks/Git/Estadistica_Inferencial/Estadistica 2 - Proyecto Final/datos1.csv")
resistencia <- DB$Resistencia
boxplot(resistencia)
hist(resistencia)
mediana <- 129.6
SIGN.test(resistencia, median= mediana, conf.level=0.95)
```
```{r}
#Base de datos 
DB <-read.csv("/Users/rudiks/Git/Estadistica_Inferencial/Estadistica 2 - Proyecto Final/datos2.csv")
#Rojos 
g_rojos <- DB$globulos_rojos
boxplot(g_rojos)
hist(g_rojos)
mediana <- 43.3
SIGN.test(g_rojos, median= mediana, conf.level=0.95)
```

```{r}
#Base de datos 
DB <-read.csv("/Users/rudiks/Git/Estadistica_Inferencial/Estadistica 2 - Proyecto Final/datos2.csv")
#Blancos 
g_blancos <- DB$globulos_blancos
boxplot(g_blancos)
hist(g_blancos)
mediana <- 7.35
SIGN.test(g_blancos, median= mediana, conf.level=0.95)
```

```{r}
#Base de datos 
DB <-read.csv("/Users/rudiks/Git/Estadistica_Inferencial/Estadistica 2 - Proyecto Final/datos3.csv")
light <- DB$Cerveza_Light_500ml
regular <- DB$Cerveza_Regular_500ml
boxplot(light,regular)
SIGN.test(light,regular, paired=TRUE, conf.level = 0.95)
```
```{r}
DB <-read.csv("/Users/rudiks/Git/Estadistica_Inferencial/Estadistica 2 - Proyecto Final/datos4.csv")
Con_expresso <- DB$Con_cafe_expresso
Sin_expresso <- DB$Sin_cafe_expresso
boxplot(Con_expresso,Sin_expresso)
wilcox.test(Con_expresso, Sin_expresso, paired=TRUE, exact=FALSE, conf.level = 0.95)
```
```{r}
DB <-read.csv("/Users/rudiks/Git/Estadistica_Inferencial/Estadistica 2 - Proyecto Final/datos5.csv")
Carsten <- DB$CarstenRainfall
Nanu <- DB$NanuRainfall
boxplot(Carsten, Nanu)
wilcox.test(Carsten, Nanu, paired=FALSE, conf.level = 0.95)
```

```{r}
DB <-read.csv("/Users/rudiks/Git/Estadistica_Inferencial/Estadistica 2 - Proyecto Final/datos6.csv")
Carsten <- DB$Carsten
Yakunai <- DB$Yakunai
Nanu <- DB$Nanu
boxplot(Carsten, Yakunai, Nanu)
kruskal.test(list(Carsten,Yakunai, Nanu))
```